"""Add user-session relationship

Revision ID: 003ca7792d9c
Revises: abb6c874ae5b
Create Date: 2024-10-15 17:33:10.281794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003ca7792d9c'
down_revision: Union[str, None] = 'abb6c874ae5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_oauth_states_state', table_name='oauth_states')
    op.drop_table('oauth_states')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_states',
    sa.Column('state', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('state', name='oauth_states_pkey')
    )
    op.create_index('ix_oauth_states_state', 'oauth_states', ['state'], unique=False)
    # ### end Alembic commands ###
