"""add is_complete in SittingSession Table

Revision ID: 1ce75a492cb1
Revises: 04b52143f0ae
Create Date: 2024-11-02 01:12:41.170660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce75a492cb1'
down_revision: Union[str, None] = '04b52143f0ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
