"""Seperate sitting_sessions for readablity

Revision ID: 7e309e6ee230
Revises: 4ed816002aa2
Create Date: 2024-10-19 11:53:50.762349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e309e6ee230'
down_revision: Union[str, None] = '4ed816002aa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sitting_sessions', sa.Column('blink', sa.JSON(), nullable=True))
    op.add_column('sitting_sessions', sa.Column('sitting', sa.JSON(), nullable=True))
    op.add_column('sitting_sessions', sa.Column('distance', sa.JSON(), nullable=True))
    op.add_column('sitting_sessions', sa.Column('thoracic', sa.JSON(), nullable=True))
    op.drop_column('sitting_sessions', 'sitting_session')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sitting_sessions', sa.Column('sitting_session', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('sitting_sessions', 'thoracic')
    op.drop_column('sitting_sessions', 'distance')
    op.drop_column('sitting_sessions', 'sitting')
    op.drop_column('sitting_sessions', 'blink')
    # ### end Alembic commands ###
