"""Add foreign keys for joined table inheritance

Revision ID: abb6c874ae5b
Revises: b62eb2123e85
Create Date: 2024-10-14 22:00:06.827169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abb6c874ae5b'
down_revision: Union[str, None] = 'b62eb2123e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_users',
    sa.Column('user_id', sa.String(length=21), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('google_users',
    sa.Column('user_id', sa.String(length=21), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('users', sa.Column('type', sa.String(length=50), nullable=True))
    op.drop_column('users', 'password')
    op.drop_column('users', 'verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('users', 'type')
    op.drop_table('google_users')
    op.drop_table('email_users')
    # ### end Alembic commands ###
