"""add device seesion

Revision ID: f3d860c469d5
Revises: f5eaca094364
Create Date: 2024-10-01 20:30:35.350721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d860c469d5'
down_revision: Union[str, None] = 'f5eaca094364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('device_info', sa.String(length=255), nullable=True))
    op.drop_constraint('user_sessions_session_id_key', 'user_sessions', type_='unique')
    op.create_index(op.f('ix_user_sessions_session_id'), 'user_sessions', ['session_id'], unique=True)
    op.drop_constraint('user_sessions_user_id_fkey', 'user_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'user_sessions', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.create_foreign_key('user_sessions_user_id_fkey', 'user_sessions', 'users', ['user_id'], ['user_id'])
    op.drop_index(op.f('ix_user_sessions_session_id'), table_name='user_sessions')
    op.create_unique_constraint('user_sessions_session_id_key', 'user_sessions', ['session_id'])
    op.drop_column('user_sessions', 'device_info')
    # ### end Alembic commands ###
