"""del Oauth Table & add user seesion Table

Revision ID: f5eaca094364
Revises: 15122e3a9c43
Create Date: 2024-09-12 20:15:36.797612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5eaca094364'
down_revision: Union[str, None] = '15122e3a9c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('user_id', sa.String(length=21), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('session_id')
    )
    op.drop_index('ix_oauth_tokens_id', table_name='oauth_tokens')
    op.drop_index('ix_oauth_tokens_refresh_token', table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.alter_column('users', 'user_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=21),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('users_user_id_seq'::regclass)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_id',
               existing_type=sa.String(length=21),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('users_user_id_seq'::regclass)"))
    op.create_table('oauth_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('expires_in', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='oauth_tokens_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='oauth_tokens_pkey')
    )
    op.create_index('ix_oauth_tokens_refresh_token', 'oauth_tokens', ['refresh_token'], unique=True)
    op.create_index('ix_oauth_tokens_id', 'oauth_tokens', ['id'], unique=False)
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
