"""Add device_identifier to user_sessions

Revision ID: f8df45b2ec48
Revises: f3d860c469d5
Create Date: 2024-10-01 20:59:49.672734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8df45b2ec48'
down_revision: Union[str, None] = 'f3d860c469d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('device_identifier', sa.String(), nullable=True))
    op.drop_column('user_sessions', 'device_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('device_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('user_sessions', 'device_identifier')
    # ### end Alembic commands ###
